# PlantVillage Class Counts

This notebook counts the number of image files in each class folder under:

- `dataset/raw/PlantVillage`

It produces a per-class table and a total image count.

In [1]:
from __future__ import annotations

from pathlib import Path

import pandas as pd

In [2]:
BASE_DIR = Path.cwd().resolve().parent
DATASET_DIR = BASE_DIR / 'dataset' / 'raw' / 'PlantVillage'

assert DATASET_DIR.exists(), DATASET_DIR
DATASET_DIR

PosixPath('/home/moeenuddin/Desktop/Deep_learning/RAGAge/RAG_Diagnostic_Agent/dataset/raw/PlantVillage')

In [3]:
def count_files_in_class(class_dir: Path) -> int:
    """Count regular files inside a single class directory."""
    return len([path for path in class_dir.iterdir() if path.is_file()])


class_counts = {
    class_dir.name: count_files_in_class(class_dir)
    for class_dir in sorted(DATASET_DIR.iterdir())
    if class_dir.is_dir()
}

counts_df = (
    pd.Series(class_counts, name='image_count')
    .sort_index()
    .rename_axis('class_name')
    .reset_index()
)
counts_df

                                     class_name  image_count
0                 Pepper__bell___Bacterial_spot          997
1                        Pepper__bell___healthy         1478
2                         Potato___Early_blight         1000
3                          Potato___Late_blight         1000
4                              Potato___healthy          152
5                         Tomato_Bacterial_spot         2127
6                           Tomato_Early_blight         1000
7                            Tomato_Late_blight         1909
8                              Tomato_Leaf_Mold          952
9                     Tomato_Septoria_leaf_spot         1771
10  Tomato_Spider_mites_Two_spotted_spider_mite         1676
11                          Tomato__Target_Spot         1404
12        Tomato__Tomato_YellowLeaf__Curl_Virus         3209
13                  Tomato__Tomato_mosaic_virus          373
14                               Tomato_healthy         1591

In [4]:
print(f'Total classes: {len(class_counts)}')
print(f'Total images: {counts_df['image_count'].sum():,}')

Total classes: 15
Total images: 20,639

In [5]:
counts_df.sort_values('image_count', ascending=False).reset_index(drop=True)

                                     class_name  image_count
0         Tomato__Tomato_YellowLeaf__Curl_Virus         3209
1                         Tomato_Bacterial_spot         2127
2                            Tomato_Late_blight         1909
3                     Tomato_Septoria_leaf_spot         1771
4   Tomato_Spider_mites_Two_spotted_spider_mite         1676
5                                Tomato_healthy         1591
6                        Pepper__bell___healthy         1478
7                           Tomato__Target_Spot         1404
8                         Potato___Early_blight         1000
9                          Potato___Late_blight         1000
10                          Tomato_Early_blight         1000
11                Pepper__bell___Bacterial_spot          997
12                             Tomato_Leaf_Mold          952
13                  Tomato__Tomato_mosaic_virus          373
14                             Potato___healthy          152